"""Generates CAPABILITIES.md for a compiled domain."""
from __future__ import annotations
from pathlib import Path
from ..ir import CPSIR, HARDWARE_PROFILES


def generate_capabilities(ir: CPSIR, out_path: Path | None = None) -> str:
    t = ir.timing
    d = ir.deployment
    yes = lambda b: "✅" if b else "❌"

    md = f"""# Capability Matrix — {ir.metadata.domain_name}

> Auto-generated by NexForge v6.0. IR hash: `{ir.content_hash()}`

## Core Capabilities

| Capability | Supported |
|------------|:---------:|
| Deterministic IR | ✅ |
| SI dimensional analysis | ✅ |
| Z3 formal verification | ✅ |
| AST safe evaluator | ✅ |
| Rate-Monotonic scheduling | {yes(t.schedulable)} |
| Dual-core deployment | {yes(d.dual_core)} |
| Deterministic replay | ✅ |
| Priority event bus | ✅ |
| Watchdog supervisor | ✅ |
| Plugin SDK | ✅ |

## Contracts

| Contract | SIL | Class | Debounce |
|----------|:---:|:-----:|:--------:|
"""
    for c in ir.safety.contracts:
        md += f"| `{c.name}` | {c.safety_level} | {c.safety_class.value} | {c.debounce_ms}ms |\n"

    md += f"""
## Timing

| Task | WCET | Utilization |
|------|:----:|:-----------:|
| Safety | {t.wcet_safety_us} µs | {t.wcet_safety_us / (1e6/t.safety_loop_hz) * 100:.1f}% |
| Control | {t.wcet_control_us} µs | {t.wcet_control_us / (1e6/t.control_loop_hz) * 100:.1f}% |
| Telemetry | {t.wcet_telemetry_us} µs | {t.wcet_telemetry_us / (1e6/t.telemetry_hz) * 100:.1f}% |

**Total U:** {t.utilization:.3f} | **Schedulable:** {yes(t.schedulable)}

## Target — `{d.target.value}`

| Resource | Available |
|----------|:---------:|
| RAM | {HARDWARE_PROFILES[d.target].ram_bytes // 1024} KB |
| Flash | {HARDWARE_PROFILES[d.target].flash_bytes // 1024} KB |
| CPU | {HARDWARE_PROFILES[d.target].cpu_mhz} MHz |
"""
    if out_path:
        out_path.write_text(md, encoding="utf-8")
    return md
